/*
This file contains static values, settings, defaults and content for immediate available to the client.
This is not a replacement for a database. No sensitive information should be stored here. 

This file can be generated by the server.
*/

export default () => ({
    content: {},
    settings: {}
});


// @status: incomplete example